SELECT USUARIO.ID, USUARIO.NOME, DEPARTAMENTO.NOME_DEP, USUARIO_1.NOME AS Lider FROM ((USUARIO INNER JOIN USUARIO USUARIO_1 ON USUARIO.ID_LIDER = USUARIO_1.ID) INNER JOIN DEPARTAMENTO ON USUARIO.ID_DEPARTAMENTO = DEPARTAMENTO.ID)

